config/routes.rb
Datrackers::Application.routes.draw do
  
    root :to => 'static#home' 

    resources :reviews
  
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    devise_for :users
    ActiveAdmin.routes(self)

   get "static/home"
   get "static/about"
   get "static/contact"

  break if ARGV.join.include? 'assets:precompile'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/review.rb
class Review < ActiveRecord::Base

  attr_accessible :review


 def sentiment_analyzer

 end


 def emotion_polarity
   @review_emotion = SadPanda.emotion(string)
   @review_polarity = SadPanda.polarity(@review.review)

 end
    
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  # GET /reviews
  # GET /reviews.json
  def index
  
    @reviews = Review.all
    @reviews_string = Review.all.to_s
    ## SAD PANDA METHODS
    @reviews_emotion = SadPanda.emotion(@reviews_string)
    @reviews_polarity = SadPanda.polarity(@reviews_string)

    # @sadpanda_emotion = SadPanda.emotion.@reviews
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end



#####SAD PANDA
# WE are trying to get polarity,emotion from SadPanda

#### SENTI MEN ALIZER
#  Methods 
###  Sentimentilizer.analyze(string)
#   result give hash
 # Sentimenttal Analyzer
 #   @review_string = @review.review.to_s
 #   @sentiment_review = Sentimentilizer.analyze(@review_string) 
    
## Hash nunchi probrability,sentiment vasthadhi 

## dhanni manam print chesi,table lo veeyyali



### We need Parse HASH 
## print probability,sentiment 

# Sentimentalizer.analyze(review.review)
# @review_json = Sentimentalizer.analyze(review.review)
# JSON.parse(@review_json)   -- Parse JSON (RESult HASH)
# @review_result = JSON.parse(@review_json)
## 
# @review_result["probability"] 
# @review_result[0].probability



# SadPanda.emotion('string')
# SadPanda.polarity(review)
# 
  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    ## SAD PANDA METHODS
    @review_emotion = SadPanda.emotion(@review.review)
    @review_polarity = SadPanda.polarity(@review.review)
    
    
    ## Sentimentalizer Methods (Analyze review String)
      # @analyze_review = Sentimentilizer.analyze(@review.review)
    ##Parsed JSON
      # @review_result    = JSON.parse(@analyze_review)

    ##Probablility
     # @review_probability = @review_result["probability"] 
    ##Sentiment
     # @review_sentiment = @review_result["sentiment"]


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end


  def tracker
    review_analyzer
  end

  def review_analizer
    user_review = JSON.parse(Review.all.to_json)
    user_review.each do |review|
    review_emotions = review["review"]
      @sentiment = JSON.parse(Sentimentalizer.analyze("#{review_emotions}"))
    end  
  end

  







 end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end

  def about
  end

  def contact
  end

 
  def index
    
  end

  

  def comment_analizer
  	user_comments = JSON.parse(Review.all.to_json)
  	user_comments.each do |comment|
      commens = comment["comments"]
      @sentiment = JSON.parse(Sentimentalizer.analyze("#{commens}"))
    end  
  end




  # def sentimentilizer_show_method
  #   ## Sentimentalizer Methods (Analyze review String)
  #     @analyze_review = Sentimentilizer.analyze(@review_string)
  #   ##Parsed JSON
  #     @review_result    = JSON.parse(@review_string)

  #   ##Probablility
  #     @review_probability = @review_result["probability"] 
  #   ##Sentiment
  #     @review_sentiment = @review_result["sentiment"]
  # end




  ## Sentimentalizer Methods (Analyze review String)
    # @analyze_review = Sentimentilizer.analyze(@review_string)
    ##Parsed JSON
    # @review_result    = JSON.parse(@review_string)

    ##Probablility
    # @review_probability = @review_result["probability"] 
    ##Sentiment
    # @review_sentiment = @review_result["sentiment"]


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header.html.erb
<div class='box photo col2'>
    <a href="#"><img src='images/prod_thumb.png' /></a>
    <h4 style="text-align:center"><strong>Reviews</strong></h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel ligula vel felis pretium gravida...</p>
    <p style="text-align:center">       
      <%= link_to "Details", reviews_path, :class => "button small radius"  %>
    </p>
</div>
            

<div class='box photo col2'>
    <a href="#"><img src='images/prod_thumb.png' /></a>
    <h4 style="text-align:center"><strong>Comments</strong></h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel ligula vel felis pretium gravida...</p>
    <p style="text-align:center">
        <%= link_to "Details", :class => "button small radius"  %>
    </p>
</div>



<!-- photo -->
<div class='box photo col2'>
    <a href="#"><img src='images/prod_thumb.png' /></a>
    <h4 style="text-align:center"><strong>Job Name</strong></h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel ligula vel felis pretium gravida...</p>
    <p style="text-align:center"><a href="#" class="button small radius">Details &raquo;</a></p>
</div>

<!-- photo -->
<div class='box photo col2'>
    <a href="#"><img src='images/prod_thumb.png' /></a>
    <h4 style="text-align:center"><strong>Job Name</strong></h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel ligula vel felis pretium gravida...</p>
    <p style="text-align:center"><a href="#" class="button small radius">Details &raquo;</a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Data Analytics" %></title>
     <%= favicon_link_tag '/assets/favicon.ico', :rel => 'shortcut icon' %>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

  </head>

  <body>
  
  <!-- Nav and Banner -->
  <div  class="row page-wrap">
    <div class="large-12 columns">

      <div class="row">
       <!-- Navigation -->
        <div class="large-12 columns">
            <nav class="top-bar" data-topbar >

              <ul class="title-area">
                <!-- Title Area -->
                <li class="name">
                  
                </li>
                <li class="toggle-topbar menu-icon">
                  <a href="#"><span>menu</span></a>
                </li>
              </ul>

     
              <section class="top-bar-section">
                <ul class="left">
                  <li class="divider"></li>
                    <li>
                      <h3>
                          <%= link_to "Data Analytics", root_path %>
                      </h3>
                    </li>
              
                  <li class="divider"></li>
                  <li>
                    <h3 style="font-family:Open Sans,Helvetica Neue,Helvetica,Helvetica,Arial,sans-serif;">
                      <%= link_to "Reviews", reviews_path %>
                    </h3>
                  </li>
                 
                  <li class="divider"></li>
                  <li>
                    <h3 style="font-family:Open Sans,Helvetica Neue,Helvetica,Helvetica,Arial,sans-serif;">
                      <%= link_to "Comments" %>
                    </h3>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <h3 style="font-family:Open Sans,Helvetica Neue,Helvetica,Helvetica,Arial,sans-serif;">
                      <a href="/static/contact">Contact Us</a>
                    </h3>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <h3 style="font-family:Open Sans,Helvetica Neue,Helvetica,Helvetica,Arial,sans-serif;">
                      <a href="/static/about">About Us</a>
                    </h3>
                  </li>
                </ul>
                
              </section>
            </nav>
            <!-- end Navigation -->
        </div>
      </div>
 
 
  <div class="row">
    <div class="large-12 columns">
 
     <!-- Desktop Slider -->
 
      <div class="hide-for-small">
        <div id="featured">
             <span><p align="center" style="font-size:70px;margin:75px ;font-family: inherit;">Data Analytics</p></span>
          </div>
        </div>
        <!-- End Desktop Slider -->
 
        <!-- Mobile Header -->
        <div class="row">
          <div class="small-12 show-for-small"><br>
            <h3 align="center" style="font-size:30px;margin:50px;">Data Analytics</h3>
          </div>
        </div>
        <!-- End Mobile Header -->
      </div>

  <br>
 

    <div class="large-12 columns">
      <div class="row">
         <div class="large-12 columns" align="center">
          <!-- Thumbnails -->
            <%= yield %>
          <!-- End Thumbnails -->
         </div>
      </div>
    </div>

 
    
    <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr>
      <div class="row">
        <div class="large-12 columns">
          <p align="center">© Copyright Data Analytics.</p>
        </div>
        
      </div>
    </div>
  </footer>
  </div>  

    <%= javascript_include_tag "application" %>
  </body>
</html>




<style type="text/css">
  .page-wrap
     {
        margin: 25px auto;
        border-radius: 3px;
        background: none repeat scroll 0% 0% rgb(255, 255, 255);
        box-shadow: 0px 1px 3px rgba(34, 25, 25, 0.4);
      }
  .top-bar
     {
        background-color: #f8f8f8;
        padding: 10px 0px 2px;
       height: 75px;
       width: 100%;
      }
  .body {
    color: rgb(51, 51, 51);
    font-size: 13px;
    line-height: 18px;
}

 .top-bar {
        height:75px;
      }
      .top-bar .name{
            height:65px;

      }
      .top-bar-section ul{
          background: #fff;
      }
      .top-bar-section ul li a{
          color: #585858;
          font-size: 16px;
      }
      .top-bar-section ul li a:hover{
          color: #73c20e;
      }
      .top-bar .toggle-topbar.menu-icon a:hover{
          background: #fff;
      }
</style>

 

app/views/reviews/_form.html.erb
<%= form_for @review, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    
    <div class="controls">
      <%= f.text_area :review, :class => 'text_area', :style => "width:400px; height:150px;" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'button redius' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reviews_path, :class => 'button redius' %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/index.html.erb
<h1 align="center">Listing reviews</h1>
<table class="table table-bordered table-striped">
  <tr>
    <th class="font">Review</th>
    <th class="font">Emotion</th>
    <th class="font">Polarity</th>&nbsp;
    <th class="font">probability</th>
    <th class="font">Sentiment</th>
    <th class="font">Actions</th>
  </tr>



<% @reviews.each do |reviews| %>
  <tr>
    <td><%= reviews.review %></td>
        
    <% @reviews_string = reviews.review.to_s %>

    <td><%=  SadPanda.emotion(reviews.review.to_s) %> </td>
    <td><%=  SadPanda.polarity(reviews.review.to_s) %> </td>
      
    <% @sentiment_states = JSON.parse(Sentimentalizer.analyze(@reviews_string)) %>
    <td>  <%= @sentiment_states["probability"] %> </td>
      <td>  <%= @sentiment_states["sentiment"] %> </td>


    <td><%= link_to 'Show', reviews_path %></td>
    <td><%= link_to 'Edit', edit_review_path(reviews) %></td>
    <td><%= link_to 'Destroy',review_path(reviews), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Review',  new_review_path , :class => "button redius" %>


<style type="text/css">
.font{
  font-size:16px;

}
</style>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reviews/show.html.erb
	<!-- Sentimentalizer -->
	<!-- Sentimentilizer.analyze(string) -->


	<!-- SAD PANDA -->
  <%  @review_string = @review.review %>
   
    <% @sentiment_state = JSON.parse(Sentimentalizer.analyze(@review_string)) %>

	    <% @sentiment_state["probability"] %> 
	    <% @sentiment_state["sentiment"] %>
      <% @review_sentiment  %>
	    <% @review_polarity  %>
	    <% @review_emotion %>

    
    <div class="large8 columns panel">
      <h1 style="text-align:center"> Review : <%= @review.review %>  </h1><hr>
        <pre>
          <h6 style="font-size:16px;">Review Probability:<%= @sentiment_state["probability"] %></h6>
          <h6 style="font-size:16px;">Review Sentiment: <%= @sentiment_state["sentiment"] %></h6>
          <h6 style="font-size:16px;">Emotions: <%= @review_emotion %></h6>
          <h6 style="font-size:16px;">Review Polarity: <%= @review_polarity %></h6>
        </pre>
    </div>
    <hr>
	    <%= link_to 'Edit', edit_review_path(@review), :class => "button redius" %> 
	    <%= link_to 'Back', reviews_path, :class => "button redius"  %>
    <hr>	
 

app/views/reviews/tracker.html.erb
tracker.html.erb